export const SEND_FIELD_SIZE_AND_BOMBS_REQUEST = "SEND_FIELD_SIZE_AND_BOMBS_REQUEST";
export const SEND_FIELD_SIZE_AND_BOMBS_SUCCESS = "SEND_FIELD_SIZE_AND_BOMBS_SUCCESS";
export const SEND_FIELD_SIZE_AND_BOMBS_FAILURE = "SEND_FIELD_SIZE_AND_BOMBS_FAILURE";
export const SEND_FIELD_SIZE_AND_BOMBS_CLEAR = "SEND_FIELD_SIZE_AND_BOMBS_CLEAR";

export const FETCH_FIELD_SIZE_AND_BOMBS_REQUEST = "FETCH_FIELD_SIZE_AND_BOMBS_REQUEST";
export const FETCH_FIELD_SIZE_AND_BOMBS_SUCCESS = "FETCH_FIELD_SIZE_AND_BOMBS_SUCCESS";
export const FETCH_FIELD_SIZE_AND_BOMBS_FAILURE = "FETCH_FIELD_SIZE_AND_BOMBS_FAILURE";
export const FETCH_FIELD_SIZE_AND_BOMBS_CLEAR = "FETCH_FIELD_SIZE_AND_BOMBS_CLEAR";

export const FETCH_FIELD_CHANGE_REQUEST = "FETCH_FIELD_CHANGE_REQUEST";
export const FETCH_FIELD_CHANGE_SUCCESS = "FETCH_FIELD_CHANGE_SUCCESS";
export const FETCH_FIELD_CHANGE_FAILURE = "FETCH_FIELD_CHANGE_FAILURE";
export const FETCH_FIELD_CHANGE_CLEAR = "FETCH_FIELD_CHANGE_CLEAR";

export const SECOND_USER_CONNECT_REQUEST = "SECOND_USER_CONNECT_REQUEST";
export const SECOND_USER_CONNECT_SUCCESS = "SECOND_USER_CONNECT_SUCCESS";
export const SECOND_USER_CONNECT_FAILURE = "SECOND_USER_CONNECT_FAILURE";
export const SECOND_USER_CONNECT_CLEAR = "SECOND_USER_CONNECT_CLEAR";

export const START_ONLINE_GAME_REQUEST = "START_ONLINE_GAME_REQUEST";
export const START_ONLINE_GAME_SUCCESS = "START_ONLINE_GAME_SUCCESS";
export const START_ONLINE_GAME_FAILURE = "START_ONLINE_GAME_FAILURE";
export const START_ONLINE_GAME_CLEAR = "START_ONLINE_GAME_CLEAR";

export const START_OFFLINE_GAME_REQUEST = "START_OFFLINE_GAME_REQUEST";
export const START_OFFLINE_GAME_SUCCESS = "START_OFFLINE_GAME_SUCCESS";
export const START_OFFLINE_GAME_FAILURE = "START_OFFLINE_GAME_FAILURE";
export const START_OFFLINE_GAME_CLEAR = "START_OFFLINE_GAME_CLEAR";